// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkR9JMdZ3byuzZARLhgS3LE9SfUZdVn2Y',
    appId: '1:146783026916:web:f2a3530c1aa9078ec1b6f1',
    messagingSenderId: '146783026916',
    projectId: 'geo-attendantgtr',
    authDomain: 'geo-attendantgtr.firebaseapp.com',
    storageBucket: 'geo-attendantgtr.firebasestorage.app',
    measurementId: 'G-41MJZP18EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDun9DF7uVEJY5G8YigFFTRNYphUJ4ToB4',
    appId: '1:146783026916:android:a8c1993e29c13dbac1b6f1',
    messagingSenderId: '146783026916',
    projectId: 'geo-attendantgtr',
    storageBucket: 'geo-attendantgtr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoMtdgTYu1cECJGbaD99yql1sYqS75Ez4',
    appId: '1:146783026916:ios:915f726e8b30b329c1b6f1',
    messagingSenderId: '146783026916',
    projectId: 'geo-attendantgtr',
    storageBucket: 'geo-attendantgtr.firebasestorage.app',
    iosBundleId: 'com.example.geoAttendanceNewUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoMtdgTYu1cECJGbaD99yql1sYqS75Ez4',
    appId: '1:146783026916:ios:915f726e8b30b329c1b6f1',
    messagingSenderId: '146783026916',
    projectId: 'geo-attendantgtr',
    storageBucket: 'geo-attendantgtr.firebasestorage.app',
    iosBundleId: 'com.example.geoAttendanceNewUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkR9JMdZ3byuzZARLhgS3LE9SfUZdVn2Y',
    appId: '1:146783026916:web:986a7debc9851e79c1b6f1',
    messagingSenderId: '146783026916',
    projectId: 'geo-attendantgtr',
    authDomain: 'geo-attendantgtr.firebaseapp.com',
    storageBucket: 'geo-attendantgtr.firebasestorage.app',
    measurementId: 'G-3G5SVL4PZV',
  );
}
